account/urls.py
from django.urls import path,include

from . import  views
#load media file
from django.conf import settings
from django.conf.urls.static import static

app_name="account"
urlpatterns = [
    path('add_user/',views.UserCreate,name='add_user'),
    path('user_list/',views.list_user,name='user_list'),
    path('update_user/<int:pk>',views.update_user,name='update_user'),
    path('delete_user/<int:pk>',views.delete_user,name="delete_user"),
    path('member_list/',views.member_list,name="member_list"),
]

ticket/urls.py
from django.contrib import admin
from django.urls import path,include

#login
from django.contrib.auth.views import LoginView,LogoutView

#view
from ticketapp import views

#load media file
from django.conf import settings
from django.conf.urls.static import static



class LoginTestView(LoginView):
  
    
    def get_context_data(self, **kwargs):
        con=super(LoginTestView,self).get_context_data(**kwargs)
        #context = super(LoginTestView, self).context
        #setting.LOGIN_REDIRECT_URL=con
        
        for d in con:
            if d=="next":
                if len(con[d])==0:
                    pass
                else:
                    settings.LOGIN_REDIRECT_URL=con[d] 
        return con

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name="index"),
    path('account/',include('account.urls'),name='account'),
    path('ticket/',include("ticketapp.urls"),name="ticket"),
    path('login/',LoginTestView.as_view(),name="login"),
    path('logout',LogoutView.as_view(),name="logout"),


]
urlpatterns  += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns  += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/models.py
from django.db import models

#import usermodel

from django.contrib.auth import get_user_model

member=get_user_model()

# Create your models here.

class Profile(models.Model):

    image=models.ImageField(upload_to="profile_pic", null=True,blank=True)
    firstname=models.CharField(max_length=50,blank=True,null=True)
    lastname=models.CharField(max_length=50,blank=True,null=True)
    phonenumber=models.CharField(max_length=11,blank=True,null=True)
    user=models.OneToOneField(member, on_delete=models.CASCADE)
    date=models.DateField(auto_now=True)


    def __str__(self):
        return self.user.username

account/forms.py
#import user model
from django.contrib.auth import get_user_model
from .models import Profile

#import form
from django import forms 

user=get_user_model()


class UserCreationForm(forms.ModelForm):
    password=forms.CharField( max_length=50, required=True,widget=forms.PasswordInput(attrs={'type':"password" ,'class':"form-control" ,'placeholder':"password"}))
    confirm_password=forms.CharField(max_length=50, required=True,widget=forms.PasswordInput(attrs={'type':"password" ,'class':"form-control" ,'placeholder':"password"}))

    class Meta():
        model=user
        fields=['username','email']

        widgets={
            'username':forms.TextInput(attrs={'type':"text" ,'class':"form-control" ,'placeholder':"Username"}),
            'email'   :forms.EmailInput(attrs={'type':"email" ,'class':"form-control" ,'placeholder':"Email"})
            
        }

    def clean_confirm_password(self):
        password=self.cleaned_data["password"]
        confirm_password=self.cleaned_data['confirm_password']
        if password==confirm_password:
            if len(password)<8:
                raise forms.ValidationError("Password Mustbe 8 digite")
            else:
                return confirm_password
        else:
            raise forms.ValidationError('Both password fields Must be same') 

                       
class ProfileForm(forms.ModelForm):
    class Meta():
        model=Profile
        fields=['firstname','lastname','image','phonenumber']            
            
        widgets={
            'firstname':forms.TextInput(attrs={'type':"text" ,'class':"form-control" ,'placeholder':"Firstname"}),
            'lastname':forms.TextInput(attrs={'type':"text" ,'class':"form-control" ,'placeholder':"Lastname"}),
            'phonenumber':forms.TextInput(attrs={'type':"text" ,'class':"form-control" ,'placeholder':"Phonenumber"}),
            'image':forms.FileInput(attrs={'class':"form-control"}),
            
            
        }    
class UserUpdateForm(forms.ModelForm):
   
    class Meta():
        model=user
        fields=['username','email','is_staff']

        widgets={
            'username':forms.TextInput(attrs={'type':"text" ,'class':"form-control" ,'placeholder':"Username"}),
            'email'   :forms.EmailInput(attrs={'type':"email" ,'class':"form-control" ,'placeholder':"Email"})
            
        }            

account/views.py
from django.shortcuts import render,get_object_or_404
from .forms import UserCreationForm,ProfileForm,UserUpdateForm
from django.contrib.auth import get_user_model
from django.core.paginator import Paginator
from django.db.models import Q
from .models import Profile as UserProfile
from django.contrib import messages
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import permission_required
from django.contrib.admin.views.decorators import staff_member_required

Member=get_user_model()

# Create your views here.

@staff_member_required(login_url="login")
def UserCreate(request):
    form=UserCreationForm()
    profileform=ProfileForm()
    if request.method=="POST":
        form=UserCreationForm(request.POST)
        profileform=ProfileForm(request.POST,request.FILES)
        if form.is_valid() and profileform.is_valid():
            user=form.save(commit=False)
            profile=profileform.save(commit=False)
            user.set_password(form.cleaned_data['password'])
            user.save()
            profile.user=user
            profile.save()
            return render(request,'index.html')


    return render(request,'add_user.html',{'form':form,'profileform':profileform})

@staff_member_required(login_url="login")
def list_user(request):
    search_result_p=[]
    if request.method=="POST":   
        search=request.POST.get("search")
        if len(search)!=0:
            search_result_p=Member.objects.filter(Q(username__contains=search)|Q(username__contains=search))  
            print(search_result_p)                                                                                               
            if len(search_result_p)==0:
                messages.error(request,'No match found')
    users=Member.objects.filter(is_staff=False)
        # users pagignator
    paginator_p = Paginator(users, 2) # Show 25 contacts per page
    users_p = request.GET.get('users')
    users_p_p = paginator_p.get_page(users_p) 
                                                  
    context={
        'users':users_p_p,
        'search':search_result_p
    }
    return render(request,'user_list.html',context)  
@staff_member_required(login_url="login")
def update_user(request,pk):
    instance=get_object_or_404(Member,pk=pk)
    instance_profile=UserProfile.objects.filter(user=instance)
    form=UserUpdateForm(instance=instance)
    for instance_profile in instance_profile:
        instance_profile=instance_profile
    profileform=ProfileForm(instance=instance_profile)
    if request.method=="POST":
        form=UserUpdateForm(request.POST,instance=instance)
        profileform=ProfileForm(request.POST,request.FILES,instance=instance_profile)
        if form.is_valid() and profileform.is_valid():
            user=form.save(commit=False)
            profile=profileform.save(commit=False)
            if request.POST['password'] and request.POST['confirm_password']:
                if request.POST["password"]==request.POST["confirm_password"]:
                    if len(request.POST['password'])>8:
                        user.set_password(request.POST['confirm_password'])    
            user.save()
            profile.save()
            messages.success(request,'update successfully')
        else:
            messages.error(request,'not Valid')       
    context={
        'form':form,
        'profileform':profileform,
        'instance':instance
    }
    return render(request,'update_user.html',context)

@staff_member_required(login_url="login")  
def delete_user(request,pk):
    Member.objects.filter(pk=pk).delete()
    messages.success(request,'Delete successfull')
    return HttpResponseRedirect(reverse('account:user_list'))

@staff_member_required(login_url="login")
def member_list(request):
    search_result_p=[]
    if request.method=="POST":   
        search=request.POST.get("search")
        if len(search)!=0:
            search_result_p=Member.objects.filter(Q(username__contains=search)|Q(username__contains=search))  
            print(search_result_p)                                                                                               
            if len(search_result_p)==0:
                messages.error(request,'No match found')
    users=Member.objects.filter(is_staff=True,is_superuser=False)
        # users pagignator
    paginator_p = Paginator(users, 2) # Show 25 contacts per page
    users_p = request.GET.get('users')
    users_p_p = paginator_p.get_page(users_p) 
                                                  
    context={
        'users':users_p_p,
        'search':search_result_p
    }
    return render(request,'user_list.html',context)  

account/templates/add_user.html
{% extends 'base.html' %}
{% block title %}
Add Employee
{% endblock %}

{% block container %}
 <!-- ============================================================== -->
                        <!-- basic form  -->
                        <!-- ============================================================== -->
                        <div class="row">
                                <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
                                    
                                    <div class="card">
                                        <h5 class="card-header">Add-User</h5>
                                        <div class="card-body">
                                            <form method="POST" enctype="multipart/form-data">
                                               
                                               <div class="form-group">
                                                  
                                                    <label for="inputText3" class="col-form-label">Username</label>
                                                    {{form.username}}
                                                </div>
                                                <div class="form-group">
                                                    <label for="inputEmail">Email address</label>
                                                    {{form.email}}
                                                    <p>We'll never share your email with anyone else.</p>
                                                </div>
                                                
                                                <div class="form-group error">
                                                        <p style="color:red;">{{form.confirm_password.errors}}</p>
                                                    <label for="inputPassword">Password</label>
                                                    {{form.password}}
                                                </div>
                                                
                                                <div class="form-group">
                                                   
                                                        <label for="inputPassword">Confirm Password</label>
                                                        {{form.confirm_password}}
                                                    </div>
                                                {{profileform.as_p}}    
                                                
                                                <input type="submit" value="Submit" class="btn btn-success">
                                            {% csrf_token %}

                                            </form>
                                        </div>
                                       
                                    </div>
                                </div>
                            </div>
                            <!-- ============================================================== -->
                            <!-- end basic form  -->
                            <!-- ============================================================== -->
{% endblock %}

account/templates/update_user.html
{% extends 'base.html' %}
{% block title %}
Update User
{% endblock %}

{% block container %}
 <!-- ============================================================== -->
                        <!-- basic form  -->
                        <!-- ============================================================== -->
                        <div class="row">
                                <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
                                    
                                    <div class="card">
                                        <h5 class="card-header">Update User</h5>
                                        <div class="card-body">
                                            <form method="POST" enctype="multipart/form-data">
                                               
                                               <div class="form-group">
                                                  
                                                    <label for="inputText3" class="col-form-label">Username</label>
                                                    {{form.username}}
                                                </div>
                                                <div class="form-group">
                                                    <label for="inputEmail">Email address</label>
                                                    {{form.email}}
                                                    <p>We'll never share your email with anyone else.</p>
                                                </div>
                                                {% if user.is_authenticated %}   
                                                {% if user.is_superuser %}
                                                <div class="form-group">
                                                    <label for="inputEmail">{{form.is_staff.label}}</label>
                                                    {{form.is_staff}}
                                                    <p>Only Admin Can change it</p>
                                                </div>
                                                {% endif %}
                                                {% endif %}
                                                <div class="form-group error">
                                                        <p style="color:red;">{{form.confirm_password.errors}}</p>
                                                    <label for="inputPassword">Password</label>
                                                    <input type="password" name="password" class="form-control" placeholder="password" maxlength="50">
                                                </div>
                                                
                                                <div class="form-group">
                                                   
                                                        <label for="inputPassword">Confirm Password</label>
                                                        <input type="password" name="confirm_password" class="form-control" placeholder="password" maxlength="50" >
                                                    </div>
                                                {{profileform.as_p}} 
                                                
                                                
                                                <input type="submit" value="Submit" class="btn btn-success">
                                            {% csrf_token %}

                                            </form>
                                        </div>
                                       
                                    </div>
                                </div>
                            </div>
                            <!-- ============================================================== -->
                            <!-- end basic form  -->
                            <!-- ============================================================== -->
{% endblock %}

account/templates/user_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
users-list
{% endblock %}
{% block container %}
<div class="row">
        <!-- ============================================================== -->
        <!-- search bar  -->
        <!-- ============================================================== -->
        <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
            <div class="card">
                <div class="card-body">

                    <form action="" method="POST" >
                        <input class="form-control form-control-lg" type="search" placeholder="Search" aria-label="Search" name="search">
                        <button class="btn btn-primary search-btn" type="submit">Search</button>
                        {% csrf_token %}
                    </form>
                </div>
            </div>
        </div>
        <!-- ============================================================== -->
        <!-- end search bar  -->
        <!-- ============================================================== -->
</div>
<div class="row">
    <!-- ============================================================== -->
                    <!-- basic table  -->
                    <!-- ============================================================== -->
                    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
                            <div class="card">
                                <h5 class="card-header">User-List</h5>
                                <div class="card-body">
                                    <div class="table-responsive">
                                        {% if users or search %}
                                        {% if search %}
                                        <table class="table table-striped table-bordered first">
                                            <thead>
                                                <tr>
                                                    <th>Username</th>
                                                    <th>Email</th>
                                                    <th>Phonenumber</th>
                                                    <th>Firstname</th>
                                                    <th>Lastname</th>
                                                    <th class="text-center"style=" width: 200px;"><a href="{% url 'account:add_user' %}" class="badge badge-success" >Add<span> </th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                {% for users in search %}
                                                <tr>
                                                    <td>{{users.username}}</td>
                                                    <td>{{users.email}}</td>
                                                    <td>{{users.profile.phonenumber}}</td>
                                                    <td>{{users.profile.firstname}}</td>
                                                    <td>{{users.profile.lastname}}</td>
                                                    <td class="text-center" style=" width: 200px; justify-content-center;"><a style=" margin-right: 10px;" href="{% url 'account:update_user' pk=users.pk %}"class="badge badge-warning">Edit</a><a href="{% url 'account:delete_user' pk=users.pk %}"class="badge badge-danger">Delete</a></td>
                                                </tr>
                                               {% endfor %}
                                        </table>
                                        {% else %}
                                        
                                       
                                        <table class="table table-striped table-bordered first">
                                            <thead>
                                                <tr>
                                                    <th>Username</th>
                                                    <th>Email</th>
                                                    <th>Phonenumber</th>
                                                    <th>Firstname</th>
                                                    <th>Lastname</th>
                                                    <th class="text-center"style=" width: 200px;"><a href="{% url 'account:add_user' %}" class="badge badge-success" >Add<span> </th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                {% for users in users %}
                                                <tr>
                                                    <td>{{users.username}}</td>
                                                    <td>{{users.email}}</td>
                                                    <td>{{users.profile.phonenumber}}</td>
                                                    <td>{{users.profile.firstname}}</td>
                                                    <td>{{users.profile.lastname}}</td>
                                                            <td class="text-center" style=" width: 200px; justify-content-center;"><a style=" margin-right: 10px;" href="{% url 'account:update_user' pk=users.pk %}"class="badge badge-warning">Edit</a><a href="{% url 'account:delete_user' pk=users.pk %}"class="badge badge-danger">Delete</a></td>
                                                </tr>
                                               {% endfor %}
                                        </table>
                                        {% endif %}
                                        {% endif %}
                                       
                                    </div>
                                    
                                </div>
                            </div>
                            {% if search %}
                            {% else %}
                            <nav aria-label="Page navigation example">
                                    <ul class="pagination">
                                       {% if users.has_previous %}
                                        <li class="page-item"><a class="page-link" href="?users=1">&laquo; first</a></li>
                                        <li class="page-item"><a class="page-link" href="?users={{ obj.previous_page_number }}">previous</a></li>
                                        {% endif %}
                                         <li class="page-item"><a class="page-link" class="page-link" href="#">Page {{ users.number }} of {{ users.paginator.num_pages }} | total users {{ users.paginator.count }}</a></li>
                                        {% if users.has_next %}
    
                                        <li class="page-item"><a class="page-link" href="?users={{ users.next_page_number }}">Next</a></li>
                                         <li class="page-item"> <a class="page-link" href="?users={{ users.paginator.num_pages }}">last &raquo;</a></li>
                                         {% endif %}
                                   </ul>
                               </nav>
                        </div>
                        {% endif %}
                        <!-- ============================================================== -->
                        <!-- end basic table  -->
                        <!-- ============================================================== -->
                       
</div>   
{% endblock %}