ticket/urls.py
from django.contrib import admin
from django.urls import path,include

#login
from django.contrib.auth.views import LoginView,LogoutView

#view
from ticketapp import views

#load media file
from django.conf import settings
from django.conf.urls.static import static



class LoginTestView(LoginView):
  
    
    def get_context_data(self, **kwargs):
        con=super(LoginTestView,self).get_context_data(**kwargs)
        #context = super(LoginTestView, self).context
        #setting.LOGIN_REDIRECT_URL=con
        
        for d in con:
            if d=="next":
                if len(con[d])==0:
                    pass
                else:
                    settings.LOGIN_REDIRECT_URL=con[d] 
        return con

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name="index"),
    path('account/',include('account.urls'),name='account'),
    path('ticket/',include("ticketapp.urls"),name="ticket"),
    path('login/',LoginTestView.as_view(),name="login"),
    path('logout',LogoutView.as_view(),name="logout"),


]
urlpatterns  += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns  += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ticketapp/urls.py
from django.urls import path,include
from . import views 
from django.conf import settings
from django.conf.urls.static import static

app_name="ticketapp"

urlpatterns=[
    path('complain_create',views.createcomplain,name='complain_create'),
    path('raise_ticket/<int:pk>',views.raisedticket,name="raise_ticket"),
    path('ticket_disc/<int:pk>',views.disc_ticket,name='ticket_disc'),
    path('conversation',views.conversation,name="conversation"),
    path('close_ticket/<int:pk>',views.closeticket,name='closeticket'),
    path('ticket_list',views.list_Ticket,name='ticket_list'),
]

ticketapp/models.py
from django.db import models
from django.contrib.auth import get_user_model

user=get_user_model()

# Create your models here.

class Complain(models.Model):
    subject=models.CharField(max_length=100,null=True,blank=True)
    complain=models.CharField(max_length=500,null=True,blank=True)
    image= models.ImageField(upload_to="complain_image",default='default.png')
    user=models.ForeignKey(user,on_delete=models.CASCADE ,null=True)
    date=models.DateField(auto_now=True)
    raised=models.BooleanField(default=False)
    status=models.BooleanField(default=False)


    def __str__(self):
        return self.subject

class Ticket(models.Model):
    complain=models.OneToOneField(Complain, on_delete=models.CASCADE)
    details=models.CharField(max_length=500,null=True,blank=True)  
    date=models.DateTimeField(auto_now=True)
    concern=models.ForeignKey(user,on_delete=models.DO_NOTHING) 
    ticket_id=models.CharField(max_length=100 ,null=True,blank=True)  
    status=models.CharField(max_length=50,choices=[('Processing','Processing'),('Solved','Solved'),('Closed','Closed')],default="Raised")



    def __str__(self):
        return self.ticket_id   

class Conversation(models.Model):
    text=models.CharField(max_length=500,null=True,blank=True)
    ticket=models.ForeignKey(Ticket, on_delete=models.CASCADE)
    user=models.ForeignKey(user,on_delete=models.DO_NOTHING,null=True)
    date=models.DateTimeField(auto_now=True)
      

    def  __str__(self):
        return self.ticket.ticket_id    

class Log(models.Model):
    message=models.CharField(max_length=100)
    date=models.DateTimeField(auto_now=True)
    user=models.ForeignKey(user,on_delete=models.CASCADE,null=True)

    def __str__(self):
        return self.message

ticketapp/forms.py
from django import forms
from .models import Complain,Ticket

class ComplainForm(forms.ModelForm):
    class Meta():
        model=Complain
        fields=['subject','complain','image']

        widgets={
            'subject':forms.TextInput(attrs={'placeholder':"Subject", "class":"form-control"}),
             'image':forms.FileInput(attrs={'class':"form-control"}),
             'complain':forms.Textarea(attrs={"class":'form-control','rows':2})
        }
        
class TicketForm(forms.ModelForm):
    class Meta():
        model=Ticket
        fields=[]

ticketapp/views.py
from django.shortcuts import render,get_object_or_404
from django.contrib.auth.decorators import login_required
from .forms import ComplainForm
from django.contrib import messages
from .models import Log,Complain,Ticket,Conversation
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.core.paginator import Paginator
from django.http import HttpResponse , HttpResponseRedirect
from django.urls import reverse
import random
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth import get_user_model
from django.db.models import Q
User=get_user_model()


# Create your views here.
@login_required
def index(request):
    if not request.user.is_staff:
        complain_form=ComplainForm()
        complain=Complain.objects.filter(raised=True,user=request.user)
        for complain in complain:
            complain=complain  
        context={
            'complain_form':complain_form,
            'complain':complain
        }
    else:    
        complain=Complain.objects.filter(status=False)
        complain_solved=Complain.objects.filter(status=True).count()
        total_client=User.objects.filter(is_staff=False).count()
        total_member=User.objects.filter(is_staff=True).count()
        # users pagignator
        paginator_c = Paginator(complain, 2) # Show 25 contacts per page
        complain_c = request.GET.get('complain')
        complain_c_c = paginator_c.get_page(complain_c) 
        context={
            'total_member':total_member,
            'total_client':total_client,
            'total_complain':len(complain),
            'total_solved':complain_solved,
            'complain':complain_c_c
        }
    return render(request,'index.html',context)
@login_required    
def createcomplain(request):
    if request.method=="POST":
        complain_form=ComplainForm(request.POST,request.FILES)
        if complain_form.is_valid():
            complain=complain_form.save(commit=False)
            complain.user=request.user
            complain.save()
            messages.success(request,'Wait our concern will takecare the issue soon')
            Log.objects.create(message="{} posted a complain".format(request.user),user=request.user)
            return HttpResponseRedirect(reverse("index"))

@staff_member_required(login_url="login")
def raisedticket(request,pk=None):

    complain=get_object_or_404(Complain,pk=pk)
    ticket=Ticket.objects.create(complain=complain,details=complain.complain,concern=request.user,ticket_id="T{}".format(random.randint(1000,50000)))
    complain.raised=True
    complain.save()
    Log.objects.create(message="{} A complain ticket has raised".format(complain.user),user=complain.user)
    messages.success(request,'A complete Ticket has raised')
    return HttpResponseRedirect(reverse('index'))

@login_required
def disc_ticket(request,pk):
    ticket=get_object_or_404(Ticket,pk=pk)
    context={
        'ticket':ticket
    }
    return render(request,'ticket.html',context)
@login_required
def conversation(request):
    if request.method=="POST":
        pk=request.POST['ticket']
        text=request.POST['message']
        ticket=get_object_or_404(Ticket,pk=pk)
        Conversation.objects.create(text=text,ticket=ticket,user=request.user)
        if request.user==ticket.concern:
            return HttpResponseRedirect(reverse('ticketapp:ticket_disc' ,kwargs={'pk': ticket.pk}))
        else:
            return HttpResponseRedirect(reverse('index'))
    else:
        return HttpResponseRedirect(reverse('index'))

@staff_member_required(login_url="login")        
def closeticket(request,pk):
    ticket=get_object_or_404(Ticket,pk=pk)
    ticket.status="solved"
    ticket.complain.raised=False
    ticket.complain.status=True
    ticket.complain.save()
    ticket.save()
    messages.success(request,'Ticket Has closed')
    return HttpResponseRedirect(reverse('index'))



@login_required
def list_Ticket(request):
    search_result_p=[]
    if request.method=="POST":   
        search=request.POST.get("search")
        if len(search)!=0:
            if request.user.is_staff:
                search_result_p=Ticket.objects.filter(Q(Ticket_id__contains=search)|Q(complain__username__contains=search))
            else:
                search_result_p=Ticket.objects.filter(ticket_id=search,complain__user=request.user)                                                                                                  
            if len(search_result_p)==0:
                messages.error(request,'No match found')
    ticket=Ticket.objects.filter(status="solved")
    ticket_user=Ticket.objects.filter(status="solved",complain__user=request.user)
        # ticket pagignator
    paginator_t = Paginator(ticket, 5) # Show 25 contacts per page
    ticket_t = request.GET.get('ticket')
    ticket_t_t = paginator_t.get_page(ticket_t) 

        # ticket pagignator
    paginator_u = Paginator(ticket_user, 5) # Show 25 contacts per page
    ticket_u = request.GET.get('ticket')
    ticket_u_u = paginator_u.get_page(ticket_u)
    if request.user.is_staff:                                               
        context={
            'ticket':ticket_t_t,
            'search':search_result_p
        }
    else:
         context={
            'ticket':ticket_u_u,
            'search':search_result_p
        }    
    return render(request,'ticket_list.html',context)  

    

ticketapp/templates/ticket.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Ticket{% endblock %}
{% block container %}
<div class="row">
    <div class="offset-xl-2 col-xl-8 col-lg-12 col-md-12 col-sm-12 col-12">
        <div class="card">
            <div class="card-header p-4">
                    <a class="pt-2 d-inline-block" ><strong>Nmae</strong>: CONCERN </a>
                
                <div class="float-right"> <h3 class="mb-0">Ticket: #{{ticket.ticket_id}}</h3>
                {{ticket.date}}</div>
            </div>
            <div class="card-body">
                <div class="row mb-4">
                    <div class="col-sm-6">
                        <h5 class="mb-3">Client:</h5>                                            
                        <h3 class="text-dark mb-1">{{ticket.complain.user.profile.firstname}} {{ticket.complain.user.profile.lastname}}</h3>
                        <div>Email: {{ticket.complain.user.email}}</div>
                        <div>Phone: {{ticket.complain.user.profile.phonenumber}}</div>
                    </div>
                    <div class="col-sm-6">
                        <h5 class="mb-3">Concern:</h5>
                        <h3 class="text-dark mb-1">{{ticket.concern.profile.firstname}} {{ticket.concern.profile.lastname}}</h3>                                            
                        
                        <div>Email: {{ticket.concern.email}}</div>
                        <div>Phone: {{ticket.concern.profile.phonenumber}}</div>
                    </div>
                </div>
                <div class="table-responsive-sm">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th class="center">S/N</th>
                                <th>Subject</th>
                                <th>Description</th>
                                <th class="right">status</th>                                    
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td class="center">1</td>
                                <td class="left strong">{{ticket.complain.subject}}</td>
                                <td class="left">{{ticket.complain.complain}}</td>
                                    <th class="right">{{ticket.status}}</th>
                                
                            </tr>
                            
                        </tbody>
                    </table>
                </div>
                <div class="row">
                    <div class="col-lg-4 col-sm-5">
                    </div>
                    
                </div>
            </div>                
          </div>
     </div>
  </div>
<div class="row">
    <div class="offset-xl-2 col-xl-8 col-lg-12 col-md-12 col-sm-12 col-12">
        <div class="row">
            <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12 m-b-60">
                <div class="simple-card">
                    <ul class="nav nav-tabs" id="myTab5" role="tablist">
                        <li class="nav-item">
                            <a class="nav-link active border-left-0" id="product-tab-1" data-toggle="tab" href="#tab-1" role="tab" aria-controls="product-tab-1" aria-selected="true">Conversation with concern</a>                        
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " id="product-tab-1" data-toggle="tab" href="#tab-2" role="tab" aria-controls="product-tab-1" aria-selected="true">Image</a>                        
                        </li>
                        {% if ticket.status == "solved" %}
                        {% else %}
						<li class="nav-item">
                            <a class="nav-link "  href="{% url 'ticketapp:closeticket' pk=ticket.pk %}" role="tab" >Close the ticket</a> 
                        </li>
                        {% endif %}
                    </ul>
                    <div class="tab-content" id="myTabContent5">
                        <div class="tab-pane fade show active" id="tab-1" role="tabpanel" aria-labelledby="product-tab-1">
                       <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12 m-b-60">
                      <div class="card">

                       

                          <div class="card-body">



                            <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12 m-b-60">

                              <form action="{% url 'ticketapp:conversation' %}" method="POST">



                                <div class="form-row">

                                  <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12 ">
                                    <div class="form-group">
                                        <textarea class="form-control" placeholder="Message" name="message"></textarea>
                                    </div>
                                  </div>

                                            <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12 ">
                                              <div class="input-group mb-3">                                               
                                                <input type="hidden"name="ticket" value={{ticket.pk}}>
                                                <button type="submit" class="btn btn-primary">Reply</button>
                                            </div>
                                            </div>
                                        </div>

                                                 {% csrf_token %}
                              </form>

                             </div>


                          </div>
						  {% if ticket.conversation_set.all %}
                          <div class="notification-list">
                              <div class="list-group">
                                {% for reply in ticket.conversation_set.all %}
                                  <a class="list-group-item list-group-item-action active">
                                      <div class="notification-info">
                                          <div class="notification-list-user-img"><img src="{{ reply.user.profile.image.url }}" alt="" class="user-avatar-md rounded-circle"></div>
                                          <div class="notification-list-user-block"><span class="notification-list-user-name">  {{reply.user}}</span>{{ reply.text }}
                                              <div class="notification-date">{{ reply.date }}</div>
                                          </div>
                                      </div>
                                  </a>
                                    {% endfor %}
                              </div>
                          </div>
								{% endif %}
                            <h5 class="card-header"></h5>

                      </div>

                    </div> 
                        </div>
						
						<!--tab2-->
						<div class="tab-pane fade " id="tab-2" role="tabpanel" aria-labelledby="product-tab-1">
						<div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12 m-b-60">
						<div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12 m-b-60"">
                                <div class="card">
                                    <img class="img-fluid" src="{{ticket.complain.image.url}}" alt="Card image cap">
                                    <div class="card-body">
                                        
                                    </div>
                                </div>
                            </div>
						</div>
						</div>
                        
                    </div>
					
					
                </div>
            </div>
        </div>
        
    </div>
</div>
{% endblock %}

ticketapp/templates/ticket_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Ticket-List
{% endblock %}
{% block container %}
<div class="row">
        <!-- ============================================================== -->
        <!-- search bar  -->
        <!-- ============================================================== -->
        <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
            <div class="card">
                <div class="card-body">

                    <form action="" method="POST" >
                        <input class="form-control form-control-lg" type="search" placeholder="Search" aria-label="Search" name="search">
                        <button class="btn btn-primary search-btn" type="submit">Search</button>
                        {% csrf_token %}
                    </form>
                </div>
            </div>
        </div>
        <!-- ============================================================== -->
        <!-- end search bar  -->
        <!-- ============================================================== -->
</div>
<div class="row">
    <!-- ============================================================== -->
                    <!-- basic table  -->
                    <!-- ============================================================== -->
                    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
                            <div class="card">
                                <h5 class="card-header">User-List</h5>
                                <div class="card-body">
                                    <div class="table-responsive">
                                        {% if ticket or search %}
                                        {% if search %}
                                        <table class="table table-striped table-bordered first">
                                            <thead>
                                                <tr>
                                                    <th>Ticket Id</th>
                                                    <th>subject</th>
                                                    <th>Status</th>
                                                    {% if user.is_staff %}
                                                    <th class="text-center"style=" width: 200px;"><a  class="badge badge-success" >Action<span> </th>
                                                    {% endif %}
                                                </tr>
                                            </thead>
                                            <tbody>
                                                {% for ticket in search %}
                                                <tr>
                                                    <td>{{ticket.ticket_id}}</td>
                                                    <td>{{ticket.complain.subject}}</td>
                                                    <td>{{ticket.status}}</td>
                                                   {% if user.is_staff %}
                                                    <td class="text-center" style=" width: 200px; justify-content-center;"><a style=" margin-right: 10px;" href="{% url 'ticketapp:ticket_disc' pk=ticket.pk %}"class="badge badge-warning">Details</a></td>
                                                    {% endif %}
                                                </tr>
                                               {% endfor %}
                                        </table>
                                        {% else %}
                                        
                                       
                                        <table class="table table-striped table-bordered first">
                                            <thead>
                                                <tr>
                                                   <th>Ticket Id</th>
                                                    <th>subject</th>
                                                    <th>Status</th>
                                                    {% if user.is_staff %}
                                                    <th class="text-center"style=" width: 200px;"><a  class="badge badge-success" >Action<span> </th>
                                                    {% endif %}
                                                </tr>
                                            </thead>
                                            <tbody>
                                                {% for ticket in ticket %}
                                                <tr>
                                                     <td>{{ticket.ticket_id}}</td>
                                                    <td>{{ticket.complain.subject}}</td>
                                                    <td>{{ticket.status}}</td>
                                                    {% if user.is_staff %}
                                                    <td class="text-center" style=" width: 200px; justify-content-center;"><a style=" margin-right: 10px;" href="{% url 'ticketapp:ticket_disc' pk=ticket.pk %}"class="badge badge-warning">Details</a></td>
                                                {% endif %}
                                                </tr>
                                               {% endfor %}
                                        </table>
                                        {% endif %}
                                        {% endif %}
                                       
                                    </div>
                                    
                                </div>
                            </div>
                            {% if search %}
                            {% else %}
                            <nav aria-label="Page navigation example">
                                    <ul class="pagination">
                                       {% if ticket.has_previous %}
                                        <li class="page-item"><a class="page-link" href="?ticket=1">&laquo; first</a></li>
                                        <li class="page-item"><a class="page-link" href="?users={{ ticket.previous_page_number }}">previous</a></li>
                                        {% endif %}
                                         <li class="page-item"><a class="page-link" class="page-link" href="#">Page {{ ticket.number }} of {{ ticket.paginator.num_pages }} | total Tickts {{ ticket.paginator.count }}</a></li>
                                        {% if ticket.has_next %}
    
                                        <li class="page-item"><a class="page-link" href="?ticket={{ ticket.next_page_number }}">Next</a></li>
                                         <li class="page-item"> <a class="page-link" href="?ticket={{ ticket.paginator.num_pages }}">last &raquo;</a></li>
                                         {% endif %}
                                   </ul>
                               </nav>
                        </div>
                        {% endif %}
                        <!-- ============================================================== -->
                        <!-- end basic table  -->
                        <!-- ============================================================== -->
                       
</div>   
{% endblock %}